apiVersion: apps/v1
kind: Deployment
metadata:
  name: groceries-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: groceries
  template:
    metadata:
      labels:
        app: groceries
    spec:
      containers:
        - name: groceries
          image: groceries:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: groceries-db-secret
                  key: DATABASE_URL
